#logging:
#  level:
#    org:
#      springframework:
#        r2dbc: TRACE
#aspect:
#  enabled: true

local:
  db:
    url: localhost:5432/stocks-db
    username: postgres
    password: asdqwe123

spring:
  codec:
    max-in-memory-size: 10MB
  r2dbc:
    url: r2dbc:postgresql://${local.db.url}
    username: ${local.db.username}
    password: ${local.db.password}
    pool:
      enabled: true
      initial-size: 10
      max-size: 20
  flyway:
    url: jdbc:postgresql://${local.db.url}
    locations: classpath:db/migration
    user: ${local.db.username}
    password: ${local.db.password}
    baseline-on-migrate: true

api:
  external:
    ref-data-url: https://api.iex.cloud/v1/data/CORE/REF_DATA?token={token}
    stock-data-url: https://api.iex.cloud/v1/data/core/quote/{symbol}?token={token}
    token: pk_ecaab92ac42e40cfb972d8baf553d6cc

service:
  number-of-companies: 200

