#logging:
#  level:
#    org:
#      springframework:
#        r2dbc: TRACE
aspect:
  enabled: true

local:
  db:
    url: localhost:5433/stocks-db
    username: postgres
    password: asdqwe123

spring:
  codec:
    max-in-memory-size: 10MB
  r2dbc:
    url: r2dbc:postgresql://localhost:5433/${local.db.url}
    username: ${local.db.username}
    password: ${local.db.password}
  flyway:
    url: jdbc:postgresql://${local.db.url}
    locations: classpath:db/migration
    user: ${local.db.username}
    password: ${local.db.password}
    baseline-on-migrate: true

api:
  external:
    ref-data-url: https://api.iex.cloud/v1/data/CORE/REF_DATA?token={token}
    stock-data-url: https://api.iex.cloud/v1/data/core/quote/{symbol}?token={token}
    token: pk_c33262f7443243b8b382872334be889e

service:
  number-of-companies: 201

